### ISSUE TITLE
mq 中缺少一个 Result 类

### ISSUE THREAD

**Issue by snycloud** [Dylan-haiji/javayh-oauth2#5]
![image](https://user-images.githubusercontent.com/18653890/80332439-6e3cf680-887d-11ea-91b7-7611a1e5dab1.png)

**Comment by yanghaiji** [comment]
@CozySnail  Reslut 类存在与javayh-commons中，依赖已经引入mq中，请先确认您的本地环境是否引入，如果一引入请进行maven update 
![image](https://user-images.githubusercontent.com/37392164/80333763-b78f4500-8881-11ea-8e85-66095f069f4a.png)

**Comment by snycloud** [comment]
好的,谢谢
